### PR TITLE
Fixed crash with Simply Jetpacks when ConArm isn't installed

### PR DESCRIPTION
**Pull request by brisingraerowing**
Simply adds a missing mod loaded check when initializing.

### CODE REVIEW

**Comment by TeamDman** [comment]
full transparency: 1.12 is out of LTS for the forge gradle toolchain and it doesn't work for older versions, so I'm not even going to try to make a build with this since I know it will just suck a lot of time and probably won't work

**Comment by brisingraerowing** [comment]
I have a built JAR that I can upload if you want.

**Comment by TeamDman** [comment]
Sure, please

**Comment by brisingraerowing** [comment]
[plustic-jars.zip](https://github.com/TeamDman/PlusTiC/files/12329865/plustic-jars.zip)

This is the main and sources JARs.

**Comment by TeamDman** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/plusticminusbad/files/4703532

In the approval queue, thanks for the fix

**Pull request merged**
